version: '3.9'

services:
  mongodb:
    image: mongo:7.0
    container_name: yallaplay_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: yallaplay
      MONGO_INITDB_ROOT_PASSWORD: yallaplay_dev_secret
      MONGO_INITDB_DATABASE: yallaplay
    volumes:
      - mongo_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: yallaplay_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:1.0.2
    container_name: yallaplay_mongo_ui
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: yallaplay
      ME_CONFIG_MONGODB_ADMINPASSWORD: yallaplay_dev_secret
      ME_CONFIG_MONGODB_URL: mongodb://yallaplay:yallaplay_dev_secret@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo_data:
  redis_data:
