export const Colors = {
  background: {
    primary:   '#FFFFFF',
    secondary: '#F8FAFC',
    elevated:  '#FFFFFF',
  },
  brand: {
    primary:   '#16A34A',
    dark:      '#15803D',
    light:     '#DCFCE7',
    muted:     '#86EFAC',
    border:    '#BBF7D0',
  },
  text: {
    primary:   '#0F172A',
    secondary: '#475569',
    tertiary:  '#94A3B8',
    inverse:   '#FFFFFF',
    brand:     '#16A34A',
  },
  border: {
    default: '#E2E8F0',
    strong:  '#CBD5E1',
    brand:   '#BBF7D0',
  },
  success:   '#16A34A',
  successBg: '#DCFCE7',
  error:     '#EF4444',
  errorBg:   '#FEE2E2',
  warning:   '#F59E0B',
  warningBg: '#FEF3C7',
  info:      '#3B82F6',
  infoBg:    '#DBEAFE',
  slot: {
    available:   '#16A34A',
    availableBg: '#DCFCE7',
    booked:      '#EF4444',
    bookedBg:    '#FEE2E2',
    pending:     '#F59E0B',
    pendingBg:   '#FEF3C7',
    closed:      '#94A3B8',
    closedBg:    '#F1F5F9',
  },
  sport: {
    football:   '#16A34A',
    basketball: '#F97316',
    tennis:     '#EAB308',
    volleyball: '#3B82F6',
    padel:      '#8B5CF6',
    squash:     '#EF4444',
    badminton:  '#06B6D4',
    swimming:   '#0EA5E9',
  },
  // glass kept for compatibility but now maps to flat values
  glass: {
    subtle:      'rgba(0,0,0,0.03)',
    light:       'rgba(0,0,0,0.04)',
    medium:      'rgba(0,0,0,0.06)',
    strong:      'rgba(0,0,0,0.08)',
    border:      '#E2E8F0',
    borderHover: '#CBD5E1',
    highlight:   'transparent',
  },
} as const;

export type ColorKey = keyof typeof Colors;
